#!/bin/bash

## BUILD WIN PATH TO ATOM.EXE ##
winUsr=$(powershell.exe \$env:username | tr -dc '[:alnum:]-._') # get windows username from PS and remove dos invisibles
atmPth=C:\\ProgramData\\$winUsr\\atom\\atom.exe # would prefer $PATH, but atom's entry does not directly lead to atom.exe

## FORMAT ARGS ##
if [[ ${1:0:1} == "~" ]] || [[ ${1:0:1} == "/" ]]; then # full path or home relative - just send args
  atmArg=$@
elif [[ ${1:0:1} == "-" ]]; then # no file but flags - insert a space between 
  atmArg=' '$@
else                   # no file or relative path
  atmArg=$PWD\\$@         # prepend pwd
fi

## BUILD WIN PATH TO FILE IN WSL ##
wslVer=$(powershell.exe wsl -l -q --running | tr -dc '[:alnum:]-._') # get wsl distro name from PS and remove dos invisibles
winPth=$(echo \\\\wsl.localhost\\$wslVer$atmArg | tr '/' '\\')  # replace / with escaped \

# excecute command with powershell and open windows atom.exe  into linux directory, BAM!
echo powershell.exe "$atmPth" "$winPth"
powershell.exe "$atmPth" "$winPth"

